### ISSUE TITLE
Implement win condition

### ISSUE THREAD

**Issue by JadenBalogh** [cosc-322-main-team/322GameOfAmazons#29]

**Comment by LoganParker** [comment]
can we add this to the localboard class? would make it easier to check if node is in a win state <3

**Comment by JadenBalogh** [comment]
> can we add this to the localboard class? would make it easier to check if node is in a win state <3

makes sense to me

**Comment by jpabadir** [comment]
This task is no longer required, at least for now. This is as per a conversation with Jaden that establishes that checking whether or not we still have moves we can do as a player is enough to know whether we lost.
