### ISSUE TITLE
Local player should play a move first when playing as black

### ISSUE THREAD

**Issue by JadenBalogh** [cosc-322-main-team/322GameOfAmazons#43]

**Comment by JadenBalogh** [comment]
Add a method to the `LocalPlayer` API that happens on first move. Maybe `onFirstMove()`. In `LocalPlayer`, this should be an abstract method, which you should implement in the subclasses of `LocalPlayer` to handle moving first. In the case of `MonteCarloPlayer`, it should just run the move method (which we should make its own method out of `onMoveReceived`.

**Comment by jpabadir** [comment]
On first move is called when game starts before any move was made if player is black.
